sonar.host.url=http://15.206.167.13:9000
sonar.projectKey=Pipeline:project
sonar.projectName=Pipeline-project
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqp_5ab0911a5c0851a99c7ccd1011fdf8cbb565f8c3
