sonar.host.url=http://3.110.40.211:9000
sonar.projectKey=Pipeline:project
sonar.projectName=Pipeline-project
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqp_90d7ef90ee164bda778eef5b8f9011ff8560a6d6
