sonar.host.url=http://13.235.69.5:9000
sonar.projectKey=Pipeline:project
sonar.projectName=Pipeline-project
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqp_8efb5c83e025ec91bf3fb8657eb9fb77a8f91411
