name: Java CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn clean install

      - name: SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog CLI
        run: |
          jfrog config add jfrog-server \
           --url=http://${{ secrets.JFROG_HOST}}:8082 \
           --access-token=${{ secrets.JFROG_CLI_TOKEN }} \
           --interactive=false

      - name: Deploy artifact to Artifactory
        run: |
          jfrog --version
          jfrog rt upload "target/simple-maven-project-1.0-SNAPSHOT.war" "local-snapshot-repo/" --server-id=jfrog-server

      - name: Deploy WAR to Tomcat
        run: |
          curl --user "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
               --upload-file target/*.war \
               "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/ecommerce&update=true"
        env:
          TOMCAT_MANAGER_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_MANAGER_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
    
